[build]
  command = "cp src/data/schedule.json netlify/functions/initial-data.json && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/admin/doctors"
  to = "/.netlify/functions/doctors"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/note"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
